    /run/numberOfThreads 1 #for parallelization
    /run/initialize
    /vis/open OGL 
    #/vis/viewer/set/viewpointVector 1 1 1 
    /vis/drawVolume 
    /vis/viewer/set/autoRefresh true 
    /vis/scene/add/trajectories smooth 
    #/vis/scene/add/axes
    /vis/scene/add/eventID
    /vis/scene/endOfEventAction accumulate 

#This is for atmospheric shower
    #/vis/ogl/set/displayListLimit 5000000

#If you want to add a scale in the viewer
    #/vis/scene/add/scale 10 cm 